version: 0.2

phases:
  install:
    runtime-versions:
     # java: openjdk8
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - ls
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(basename ./target/*.jar)
      - pwd

artifacts:
  files:
    - target/pay-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - Dockerfile
    - kubernetes/*
    - beforeInstall.sh
    - afterInstall.sh
  discard-paths: yes
