#server:
#  port: 8080
---

spring:
  profiles: default
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://amf-3-2-onepostest.ckputrdkt11j.ap-northeast-2.rds.amazonaws.com:3306/ONEPOS?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: chlrkddlwh

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  # profiles: default
  # h2: # H2 사용시 웹브라우져 DB 접속 http://localhost:8081/h2-console
  #   console:
  #     enabled: true
  #     path: /h2-console

  cloud:
    stream:
      kafka:
        binder:
          # brokers: localhost:29092 #Gitpod
          #brokers: localhost:9092 #로컬
          brokers: 15.165.7.195:9092 #EC2 설치 kafka
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order #각자 다르게 지정. 토픽은 onepos로 고정
          destination: onepos
          contentType: application/json
        event-out:
          destination: onepos
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8090

api:
  delivery:
    url: http://localhost:8082

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    # 전역설정
    default:
      execution.isolation.thread.timeoutInMilliseconds: 610
---

spring:
  profiles: docker
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://amf-3-2-onepostest.ckputrdkt11j.ap-northeast-2.rds.amazonaws.com:3306/ONEPOS?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: chlrkddlwh

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  cloud:
    stream:
      kafka:
        binder:
          # brokers: my-kafka.kafka.svc.cluster.local:9092
          brokers: 15.165.7.195:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: onepos
          contentType: application/json
        event-out:
          destination: onepos
          contentType: application/json

api:
  delivery:
    url: http://delivery:8080

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    # 전역설정
    default:
      execution.isolation.thread.timeoutInMilliseconds: 610
